### ISSUE TITLE
Error during use 

### ISSUE THREAD

**Issue by groponp** [mms-fcul/PypKa#23]
Dear all, 

I've installed the tool (pypka) using pip3 install pypka inside a conda envs, during these step, I do not have  any error, but when i running using :  python3 -m pypka parm.dat, where "parm.dat" is: 
```bash
structure       = 4lzt.pdb      # Input structure file name
ncpus           = -1            # Number of processes (-1 for maximum allowed)
epsin           = 15            # Dielectric constant of the protein
ionicstr        = 0.1           # Ionic strength of the medium (M)
pbc_dimensions  = 0             # PB periodic boundary conditions (0 for solvated proteins and 2 for lipidic systems)
sites           = all           # Titrate all available sites
output          = pKas.out      # pKa values output file
structure_output = out.pdb, 3, charmm  # Output structure with the most likely protonation state at a given pH value
# filename, pH value, force field ("gromos_cph", "charmm")
pH = 3                          # pH range
```
Then given me a error: 
```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/groponp/miniconda3/envs/pypka/lib/python3.13/site-packages/pypka/__init__.py", line 5, in <module>
    from .main import Titration, getTitrableSites
  File "/home/groponp/miniconda3/envs/pypka/lib/python3.13/site-packages/pypka/main.py", line 3, in <module>
    from delphi4py import DelPhi4py
  File "/home/groponp/miniconda3/envs/pypka/lib/python3.13/site-packages/delphi4py/__init__.py", line 1, in <module>
    from .delphi4py import DelPhi4py
  File "/home/groponp/miniconda3/envs/pypka/lib/python3.13/site-packages/delphi4py/delphi4py.py", line 3, in <module>
    from delphi4py.readFiles import readFiles as readF
ImportError: cannot import name 'readFiles' from 'delphi4py.readFiles' (unknown location)
```

Please  I need help.

**Comment by pedrishi** [comment]
Hi! Could you share in which platform you are and the python version?

**Comment by groponp** [comment]
Hi, off course: 

```bash 
os: Debian GNU/Linux 12 (bookworm) x86_64 
kernel: 6.1.0-26-amd64

python: Python 3.13.0
```

**Comment by brendaferrari** [comment]
Hi, I am having the same problem

```
OS: Windows WSL (running Ubuntu 22.04.3 LTS)
python: Python 3.11.10
```

**Comment by EduCubillos** [comment]
Hi, I am having the same issue 

```
from.delphi4py import DelPhi4py
  File "/home/eduardo/Apps/anaconda3/lib/python3.11/site-packages/delphi4py/delphi4py.py", line 3, in <module>
    from delphi4py.readFiles import readFiles as readF
ImportError: cannot import name 'readFiles' from 'delphi4py.readFiles' (unknown location)
```

**Comment by pedrishi** [comment]
sorry for the late reply guys.

in pypka there are few files that need to be distributed compiled. there were a few changes introduced to numpy 2.0 that affected these. we are currently trying to fix these issues.

in the meanwhile please use pypka [via docker](https://pypka.readthedocs.io/en/latest/getting_started/installation.html#via-docker) or with python versions 3.6 to 3.10
